query GetBlog($id: ID!) {
  getBlog(id: $id) {
    _id
    title
    content
    authorName
    author {
      _id
      first_name
      last_name
      email
      username
      phone_number
      country
      Address
      status
      date_of_birth
      gender
      profile_picture
      bio
      Socials
      tier_id
      preferredLanguage
      onboarding
      user_id
      age
      coins
      xp
      following
      follower
    }
    tags
    like
    createdAt
    updatedAt
    category {
      _id
      name
    }
  }
}
